<h1>Thêm Bài Viết</h1>
<div class="container">
    <form method='POST' action="<?php echo $block->getUrl('aht_example2/index/save') ?>">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" placeholder="Enter a name post" name="name">
        </div>

        <div class="form-group">
            <label for="url">Url Key</label>
            <input type="text" class="form-control" id="url" placeholder="Enter URL key post" name="url">
        </div>
        <div class="form-group">
            <label for="content">Content</label>
            <input type="text" class="form-control" id="content" placeholder="Enter content post" name="content">
        </div>
        <div class="form-group">
            <label for="status">Status</label>
            <input type="text" class="form-control" id="status" placeholder="Enter status" name="status">
        </div>
        <button type="submit" class="btn btn-primary" name="createbtn">Submit</button>
    </form>
</div>

